const Data = [
    {
        id: 1,
        image: "images/portfolio/p1.jpg",
        name: "HP",
        category: "Laptop",
        price: "580$",
        description: "Lorem ipsum dolor sit amet, incididunt ut labore et dolore magna aliqua",
    },
    {
        id: 2,
        image: "images/portfolio/p2.jpg",
        name: "Samsung",
        category: "Phone",
        price: "340$",
        description: "Lorem ipsum dolor sit amet, incididunt ut labore et dolore magna aliqua",
    },
    {
        id: 3,
        image: "images/portfolio/p3.jpg",
        name: "LG",
        category: "Camera",
        price: "320$",
        description: "Lorem ipsum dolor sit amet, incididunt ut labore et dolore magna aliqua",
    },
    {
        id: 4,
        image: "images/portfolio/p4.jpg",
        name: "Dell",
        category: "Laptop",
        price: "680$",
        description: "Lorem ipsum dolor sit amet, incididunt ut labore et dolore magna aliqua",
    },
    {
        id: 5,
        image: "images/portfolio/p7.jpg",
        name: "Sonata",
        category: "Watch",
        price: "260$",
        description: "Lorem ipsum dolor sit amet, incididunt ut labore et dolore magna aliqua",
    },
    {
        id: 6,
        image: "images/portfolio/p5.jpg",
        name: "Micomax",
        category: "TV",
        price: "800$",
        description: "Lorem ipsum dolor sit amet, incididunt ut labore et dolore magna aliqua",
    },
    {
        id: 7,
        image: "images/portfolio/p6.jpg",
        name: "Apple",
        category: "Phone",
        price: "600$",
        description: "Lorem ipsum dolor sit amet, incididunt ut labore et dolore magna aliqua",
    },
]

export default Data;